version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.2
    depends_on:
      keycloak-db:
        condition: service_healthy
    ports:
      - "8000:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
    command:
      - start-dev

  keycloak-db:
    image: postgres:12.4
    healthcheck:
      test: su - postgres -c "psql -U postgres keycloak -c 'SELECT 1;' | grep '1 row' || exit 1"
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  keycloak-setup:
    image: everpeace/curl-jq
    healthcheck:
      test: test -e /tmp/READY || exit 1
      interval: 10s
      timeout: 10s
      retries: 15
    environment:
      KEYCLOAK_URL_BASE: http://keycloak:8080
      KEYCLOAK_REALM: master
      KEYCLOAK_CLIENT_ID: spring-react
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak-setup.sh:/tmp/keycloak-setup.sh
      - ./src/main/resources/frontend/.env.dev.keycloak:/tmp/.env
    entrypoint: /bin/sh -c "/tmp/keycloak-setup.sh"
