spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: 'jdbc:h2:mem:ff8;TRUNCATE_LARGE_LENGTH=TRUE;DATABASE_TO_UPPER=FALSE'
    hikari:
      auto-commit: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8000/realms/master

server:
  error:
    whitelabel:
      enabled: false

# app:
#   security:
#     requests:
#       - uri: {URI that must be protected}
#         methods:
#           (None: Default, Same as when setting all methods.)
#           - GET
#           - POST
#           - PUT
#           - PATCH
#           - DELETE
#           - OPTIONS
#         authorities:
#           (None: Default, Same as when only authenticated.)
#           - authorityName1
#           - authorityName2
#           - ...
#     cors:
#       allowed-origins:
#         (None: Default, Cross-origin requests are not allowed.)
#         - https:// ...
#         - http:// ...
app:
  security:
    requests:
      - uri: /api/items/**
      - uri: /api/weapons/**
        authorities:
          - admin
      - uri: /api/cards/**
