spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:mem:ff8;TRUNCATE_LARGE_LENGTH=TRUE;DATABASE_TO_UPPER=FALSE
    hikari:
      auto-commit: false
  thymeleaf:
    prefix: classpath:/report/templates/
  security:
    oauth2:
      resourceserver:
        jwt:
          # Keycloak
          #issuer-uri: http://localhost:8000/realms/master
          # Cognito
          #issuer-uri: https://cognito-idp.ap-northeast-1.amazonaws.com/{{cognito-user-pool-id}}

server:
  error:
    whitelabel:
      enabled: false

app:
  report:
    fonts:
      gothic:
        name: Gothic
        resource: classpath:report/fonts/ipagp.ttf
      gothic-monospace:
        name: GothicMonospace
        resource: classpath:report/fonts/ipag.ttf

  # security:
  #   idp: {keycloak|cognito}
  #   requests:
  #     - uri: {URI that must be protected}
  #       methods:
  #         (None: Default, Same as when setting all methods.)
  #         - GET
  #         - POST
  #         - PUT
  #         - PATCH
  #         - DELETE
  #         - OPTIONS
  #       authorities:
  #         (None: Default, Same as when only authenticated.)
  #         - authorityName1
  #         - authorityName2
  #         - ...
  #   cors:
  #     allowed-origins:
  #       (None: Default, Cross-origin requests are not allowed.)
  #       - https:// ...
  #       - http:// ...
  security:
    requests:
      - uri: /api/items/**
      - uri: /api/weapons/**
        authorities:
          - admin
      - uri: /api/cards/**
